from typing import Protocol


class GatewayClient(Protocol):
    def browse_directory(self, path: str, *, include_hidden: bool = False): ...
    def inspect_file(self, path: str): ...
    def read_safe_table(self, path: str, *, offset: int = 0, limit: int = 200): ...
    def read_safe_text(self, path: str, *, max_chars: int = 50_000): ...
    def health(self): ...
